server:
  port: 8081
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/django?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    url: ${datasource.mysql.url}
#    username: root
    username: ${datasource.mysql.username}
    password: root
    driver-class-name: ${datasource.mysql.driverClassName}

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  page-size-zero: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
