server:
  port: 8081
  shutdown: graceful
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/django?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    url: ${datasource.mysql.url}
#    username: root
    username: ${datasource.mysql.username}
    password: ">,oX8.Qr9(3*7q"
    driver-class-name: ${datasource.mysql.driverClassName}

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  page-size-zero: true

